# Generated by Django 6.0.4 on 2026-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftstate',
            name='max_legendaries',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draftstate',
            name='max_mythicals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draftstate',
            name='max_paradox',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draftstate',
            name='max_ultra_beasts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draftstate',
            name='pick_timer_seconds',
            field=models.IntegerField(default=90),
        ),
    ]
