# Generated by Django 6.0.4 on 2026-05-04 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_draftstate_max_legendaries_draftstate_max_mythicals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftstate',
            name='turn_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
